### ISSUE TITLE
something missing with the steps

### ISSUE THREAD

**Issue by nf24eg** [2b12WNu4tpUF7CL4ua79z6QtxePjM9zgxgBO404/InstaCollector#1]
as a newbie to Git and python I try to understand how that code should work but seems that there is a missing step on where shall I import this code ? 
I installed instaloader but don't know whats after !

**Comment by 2b12WNu4tpUF7CL4ua79z6QtxePjM9zgxgBO404** [comment]
Hi, thanks for your comment. I was a bit drunk when I wrote this program.

Thanks for bringing this to my attention.

The libraries for the current version on the GitHub repo I am using are:

- tqdm
- colorama
- instaloader

You can install all of these using `pip3 install tqdm`, `pip3 install colorama`, and `pip3 install instaloader`. After that, try running the program again.

Also running  `pip3 install --upgrade pip` now and then is also good practice.

I am little shy and introverted so I hope this information helps.
